# Site settings
name: Magenta Blog
email: 1576514162@qq.com
author: Magenta
# baseurl: "/LessOrMore"

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

# github_username: luoyan35714

# Build settings
markdown: kramdown

# baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

