# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Magenta"
description: > # this means to ignore newlines until "email:"
   A Jekyll theme - Medium inspired

email: 1576514162@qq.com

# blog cover
cover: "/assets/images/infinity-3979296.jpg"

paginate:	5

url: "https://mingasd.github.io/" # the base hostname & protocol for your site
baseurl: ""

#google_analytics: UA-XXXXX-X


  - icon:	github
    url:	https://github.com/Mingasd
    desc:	Fork me on github
