# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "Magenta"
description:        "嘴里塞满糖果"

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-seo-tag
